Fix/#66 Navigation Bar UI 수정
SV-Team-B/frontend pull request #67
Opened 2023-01-24 07:06 UTC by nowrobin

## 추가한 기능 설명

네비게이션 UI   수정 

<br>

## check list

- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?

2023-01-24 08:06 UTC, sangminlee98 requested changes
메인페이지에서 네브바로 기능을 옮겨야 돼서 귀찮았을텐데 잘 해주셔서 감사합니다!
UI부분 코멘트 달은 곳만 수정해서 다시 PR 업데이트 해주시면 될것같아요!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  height: 4rem;
이 네브바 같은 경우에는 언더라인(쉐도우)는 화면끝에서 끝까지 있어야하므로 따로 바깥 컨테이너를 선언해서 width를 100%로 주고 shadow를 줘야합니다!
지금같은경우는 1400 이상에서는 뚝 끊긴 느낌이 들어요!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
데스크탑에만 height을 미디어쿼리를 주니까 태블릿 사이즈에서는 커지는데 데스크탑에서 다시 작아지는게 살짝 부자연스러운 것 같아요!
desktop말고 tablet에 주면 어떨까요?

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
이것도 위에 코멘트랑 마찬가지입니다!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
마찬가지입니다!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
마찬가지입니다!
그리고 margin이 데스크탑에만 좁고 모바일 태블릿사이즈에서는 커서 통일성이 조금 없어보일 수 있어요!
margin은 미디어쿼리 주지 말고 그냥 해도 될것같아요!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
마찬가지입니다!

2023-01-24 08:06 UTC, sangminlee98 commented on src/components/NavigationBar/styles.module.scss
> +  }
여기도요!

2023-01-24 08:22 UTC, nowrobin commented on src/components/NavigationBar/styles.module.scss
> +  }
넵  확실히 어색하네요 이부분은 하나씩 수정해보겠습니다

2023-01-24 08:25 UTC, nowrobin commented on src/components/NavigationBar/styles.module.scss
> +  height: 4rem;
검색하는 부분을   space between 으로 줘서  width를 너무 따라가서 좀 가려지더라고요,  이부분도 고쳐보겠습니다 .

2023-01-24 08:26 UTC, nowrobin commented on src/components/NavigationBar/styles.module.scss
> +  }
desktop 기준으로 맞추면 mobile 에서는 너무 작아서 ,  mobile로 맞추고 아에 하나씩 수정하는식으로 해야될꺼같아요 .

2023-01-24 14:34 UTC, AlgeMoya approved these changes
옮겨진 부분들 확인했습니다. 함께했으면 좋았을텐데 못해서 아쉽네요 ㅠ 수고 많으셨습니다!

2023-01-24 14:34 UTC, AlgeMoya commented on src/components/NavigationBar/styles.module.scss
> +  height: 4rem;
네 저도 동의합니다. 웬만하면 px보다는 %나 rem 등으로 맞추는 습관을 저도 들여야겠네요.

2023-01-24 14:34 UTC, AlgeMoya commented on src/components/NavigationBar/styles.module.scss
> +  }
혹시 사이즈 변경 시에 커졌다 작아지는 것도 애니메이션 처리를 해보면 어떨까 싶네요. 그냥 후순위로 생각합시다 ㅎ

2023-01-26 06:27 UTC, sangminlee98 approved these changes
확인했습니다! 고생하셨습니다.

2023-01-26 06:28 UTC, merged